language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
after_success: npm run docs
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  keep-history: true
  on:
    branch: master
    repo: r-spacex/rocketsass
- provider: npm
  email: richikscdev@outlook.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: r-spacex/rocketsass
